name: Generate ASCII Artwork

on: 
    workflow_dispatch

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: List of Repository Files
          run: ls -ltra

        - name: Debug - List Files Before Script Execution
          run: |
            echo "--- Listing files in current directory before chmod ---"
            ls -al .
            echo "--- Listing files in .github/workflows directory ---" # Just in case
            ls -al .github/workflows/
            echo "--- Listing files recursively from root ---"
            ls -R

        - name: Read Shell Script
          run: |
            echo "Initiated loading shell script for reading..."
            cat ascii-script.sh
            echo "Finished reading shell script"
            ls -al

        - name: Executing Shell Script
          run: |
            # IMPORTANT: Confirm 'ascii-script.sh' is in the output of the 'ls -al .' above
            chmod +x ascii-script.sh
            ./ascii-script.sh

        

